{% set name = "editdistance" %}
{% set version = "0.5.3" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.tar.gz'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  'sha256': '89d016dda04649b2c49e12b34337755a7b612bfd690420edd50ab31787120c1f'

build:
  number: 3
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
  run:
    - python

test:
  source_files:
    - test
  imports:
    - editdistance
  commands:
    - python test/test_editdistance.py

about:
  home: https://www.github.com/aflc/editdistance
  license: MIT
  license_family: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Fast implementation of the edit distance(Levenshtein distance)'
  description: "Fast implementation of the edit distance(Levenshtein distance)"
  doc_url: https://github.com/aflc/editdistance
  dev_url: https://github.com/aflc/editdistance

extra:
  recipe-maintainers:
    - nelson-liu
