{% set name = "editdistance" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/roy-ht/editdistance/archive/v{{ version }}.tar.gz
  sha256: 650c5f15083af274bcedbb3832b5f6570fc79f67171cc0cbdc83fb7cd0de18a8

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - cython
  run:
    - python

test:
  source_files:
    - test
  imports:
    - editdistance
  commands:
    - python test/test_editdistance.py

about:
  home: https://www.github.com/aflc/editdistance
  license: MIT
  license_family: MIT
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Fast implementation of the edit distance(Levenshtein distance)
  description: Fast implementation of the edit distance(Levenshtein distance)
  doc_url: https://github.com/aflc/editdistance
  dev_url: https://github.com/aflc/editdistance

extra:
  recipe-maintainers:
    - nelson-liu
    - notestaff
